name: crontab_cache_to_dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'  # 每月1号的凌晨4点
#  push:
#    paths:
#      - 'node.Dockerfile'
#      - 'cache.install.Dockerfile'
#      - 'cache.build.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: node.Dockerfile
          push: true
          tags: sijinhui/node:base
          platforms: linux/amd64,linux/arm64
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cache.install.Dockerfile
          push: true
          tags: sijinhui/chatgpt-next-web:installcache
          platforms: linux/amd64,linux/arm64
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cache.build.Dockerfile
          push: true
          tags: sijinhui/chatgpt-next-web:buildcache
          platforms: linux/amd64,linux/arm64
